### ISSUE TITLE
IndexError: winning move has no ponder

### ISSUE THREAD

**Issue by L0laapk3** [iamjarret/pystockfish#11]
in def bestmove:

i suggest the following fix:

instead of

                     return {'move': split_text[1],
                            'ponder': split_text[3],
                            'info': last_line
                    }

use:

                try:
                    return {'move': split_text[1],
                            'ponder': split_text[3],
                            'info': last_line
                    }
                except IndexError:
                    return {'move': split_text[1],
                            'ponder': '-',
                            'info': last_line
                    }

**Comment by iamjarret** [comment]
Thanks for pointing this out, L0laapk3.  I added a fix in 7678a025c5 with an if clause.
